-- GENERATED by tools/build-supabase-sql.js — do not edit by hand.
-- Source of truth: DB.SCHEMA in src/Sheets.gs
--
-- Run this once in the Supabase SQL editor. Safe to re-run: it only
-- creates what is missing and never drops a table that holds data.

create table if not exists public.assets (
  row_id bigint generated always as identity primary key,
  asset_id text,
  asset_tag text,
  category text,
  subcategory text,
  make text,
  model text,
  serial_number text,
  status text,
  condition text,
  ownership text,
  rental_vendor_id text,
  rental_start date,
  rental_end date,
  assigned_to_emp_id text,
  assigned_on date,
  location_id text,
  purchase_date date,
  purchase_cost numeric,
  currency text,
  po_number text,
  invoice_number text,
  vendor_id text,
  warranty_start date,
  warranty_end date,
  amc_vendor_id text,
  amc_start date,
  amc_end date,
  specs text,
  notes text,
  created_at timestamptz,
  created_by text,
  updated_at timestamptz,
  updated_by text
);
create index if not exists assets_asset_id_idx on public.assets (lower(asset_id));

create table if not exists public.assignments (
  row_id bigint generated always as identity primary key,
  assignment_id text,
  asset_id text,
  emp_id text,
  from_location_id text,
  to_location_id text,
  action text,
  assigned_on date,
  returned_on date,
  condition_out text,
  condition_in text,
  acknowledged boolean,
  remarks text,
  created_at timestamptz,
  created_by text
);
create index if not exists assignments_assignment_id_idx on public.assignments (lower(assignment_id));

create table if not exists public.maintenance (
  row_id bigint generated always as identity primary key,
  maintenance_id text,
  asset_id text,
  type text,
  reported_on date,
  reported_by text,
  issue text,
  vendor_id text,
  sent_on date,
  returned_on date,
  resolution text,
  cost numeric,
  under_warranty boolean,
  status text,
  created_at timestamptz,
  created_by text
);
create index if not exists maintenance_maintenance_id_idx on public.maintenance (lower(maintenance_id));

create table if not exists public.employees (
  row_id bigint generated always as identity primary key,
  emp_id text,
  full_name text,
  email text,
  department text,
  designation text,
  location_id text,
  manager_email text,
  status text,
  date_joined date,
  date_exited date
);
create index if not exists employees_emp_id_idx on public.employees (lower(emp_id));

create table if not exists public.locations (
  row_id bigint generated always as identity primary key,
  location_id text,
  name text,
  type text,
  city text,
  state text,
  country text,
  address text,
  active boolean
);
create index if not exists locations_location_id_idx on public.locations (lower(location_id));

create table if not exists public.vendors (
  row_id bigint generated always as identity primary key,
  vendor_id text,
  name text,
  type text,
  contact_person text,
  email text,
  phone text,
  gstin text,
  address text,
  notes text,
  active boolean
);
create index if not exists vendors_vendor_id_idx on public.vendors (lower(vendor_id));

create table if not exists public.users (
  row_id bigint generated always as identity primary key,
  email text,
  name text,
  role text,
  active boolean
);
create index if not exists users_email_idx on public.users (lower(email));

create table if not exists public.auditlog (
  row_id bigint generated always as identity primary key,
  log_id text,
  timestamp timestamptz,
  user_email text,
  entity text,
  entity_id text,
  action text,
  field text,
  old_value text,
  new_value text,
  source text
);
create index if not exists auditlog_log_id_idx on public.auditlog (lower(log_id));

create table if not exists public.config (
  row_id bigint generated always as identity primary key,
  key text,
  value text
);

-- Fast lookups the app leans on.
create index if not exists assets_serial_idx on public.assets (lower(serial_number));
create index if not exists assets_status_idx on public.assets (status);
create index if not exists assignments_asset_idx on public.assignments (asset_id);
create index if not exists maintenance_asset_idx on public.maintenance (asset_id);
create index if not exists auditlog_entity_idx on public.auditlog (entity_id);

-- The write mutex. One row, updated atomically to claim the lock.
create table if not exists public._system (
  id int primary key default 1,
  token text,
  locked_at timestamptz,
  label text,
  constraint _system_single_row check (id = 1)
);
insert into public._system (id) values (1) on conflict (id) do nothing;

-- Sign-in credentials. Kept apart from the Users table so that table
-- stays exactly the schema the app expects.
create table if not exists public.auth_credentials (
  email text primary key,
  password_hash text not null,
  must_change boolean not null default true,
  failed_attempts int not null default 0,
  locked_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Every table is reachable only by the service role, which the Netlify
-- functions hold. Enabling RLS with no policies denies the anon key
-- outright, so a leaked public key exposes nothing.
alter table public.assets enable row level security;
alter table public.assignments enable row level security;
alter table public.maintenance enable row level security;
alter table public.employees enable row level security;
alter table public.locations enable row level security;
alter table public.vendors enable row level security;
alter table public.users enable row level security;
alter table public.auditlog enable row level security;
alter table public.config enable row level security;
alter table public._system enable row level security;
alter table public.auth_credentials enable row level security;

-- Config seed: the dropdown lists every screen reads from.
insert into public.config (key, value)
select * from (values
  ('category', 'Laptop'),
  ('category', 'Desktop'),
  ('category', 'Mobile'),
  ('category', 'Tablet'),
  ('category', 'Monitor'),
  ('category', 'Headset'),
  ('category', 'Accessory'),
  ('category', 'Printer'),
  ('category', 'Scanner'),
  ('category', 'Router'),
  ('category', 'Switch'),
  ('category', 'Firewall'),
  ('category', 'Access Point'),
  ('category', 'Server'),
  ('category', 'Storage'),
  ('category', 'UPS'),
  ('category', 'Projector'),
  ('category', 'Furniture'),
  ('category', 'Office Equipment'),
  ('category', 'Consumable'),
  ('category', 'Other'),
  ('status', 'In Stock'),
  ('status', 'Assigned'),
  ('status', 'In Repair'),
  ('status', 'Retired'),
  ('status', 'Lost'),
  ('status', 'Returned to Vendor'),
  ('condition', 'New'),
  ('condition', 'Good'),
  ('condition', 'Fair'),
  ('condition', 'Damaged'),
  ('ownership', 'Owned'),
  ('ownership', 'Rented'),
  ('ownership', 'Leased'),
  ('maintenance_type', 'Repair'),
  ('maintenance_type', 'Preventive'),
  ('maintenance_type', 'Upgrade'),
  ('maintenance_type', 'Replacement'),
  ('maintenance_type', 'AMC Service'),
  ('maintenance_status', 'Open'),
  ('maintenance_status', 'In Progress'),
  ('maintenance_status', 'Closed'),
  ('maintenance_status', 'Cancelled'),
  ('location_type', 'Office'),
  ('location_type', 'Warehouse'),
  ('location_type', 'Remote'),
  ('location_type', 'Client Site'),
  ('vendor_type', 'Supplier'),
  ('vendor_type', 'Rental'),
  ('vendor_type', 'AMC'),
  ('vendor_type', 'Service'),
  ('department', 'Engineering'),
  ('department', 'Sales'),
  ('department', 'Marketing'),
  ('department', 'Support'),
  ('department', 'Finance'),
  ('department', 'HR'),
  ('department', 'IT'),
  ('department', 'Operations'),
  ('department', 'Legal'),
  ('department', 'Admin'),
  ('currency', 'INR'),
  ('currency', 'USD'),
  ('currency', 'EUR'),
  ('currency', 'GBP'),
  ('currency', 'SGD'),
  ('currency', 'AED')
) as seed(key, value)
where not exists (select 1 from public.config);
