/**
 * build-logic.js — bundles the .gs business logic into a module the Netlify
 * functions can require.
 *
 * Why a generated string rather than reading /src at runtime: bundled functions
 * only ship what the bundler can see statically. Embedding the source removes
 * any dependency on included_files, __dirname or the deploy layout.
 *
 * Run before deploying functions. netlify.toml does this for you.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'netlify', 'functions', '_lib', 'logic-bundle.js');

// Load order matches Apps Script (alphabetical). Every file is included,
// Sheets.gs included: its SpreadsheetApp calls hit the in-memory grid shim.
function build() {
  const files = fs.readdirSync(SRC).filter(f => f.endsWith('.gs')).sort();
  if (!files.length) throw new Error('No .gs files found in ' + SRC);

  const parts = files.map(f => {
    const body = fs.readFileSync(path.join(SRC, f), 'utf8');
    return '/* ==== ' + f + ' ==== */\n' + body;
  });

  const source = parts.join('\n\n');
  const out =
    '/* GENERATED by tools/build-logic.js — do not edit.\n' +
    ' * Source of truth: /src/*.gs (' + files.join(', ') + ')\n' +
    ' */\n' +
    'module.exports = {\n' +
    '  files: ' + JSON.stringify(files) + ',\n' +
    '  bytes: ' + source.length + ',\n' +
    '  source: ' + JSON.stringify(source) + '\n' +
    '};\n';

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);
  console.log('Bundled ' + files.length + ' logic files (' + Math.round(source.length / 1024) + ' KB) into ' +
    path.relative(ROOT, OUT));
}

build();
