/**
 * build.js — generates the static bundle in ./public.
 *
 *   node build.js                  demo build: logic runs in the browser
 *   node build.js --backend=http   real build: logic runs in Netlify Functions
 *
 * There is no bundler and no npm dependency on purpose. This script only
 * extracts and copies, so /src stays the single source of truth: the Apps
 * Script project, the demo build and the Netlify build never drift.
 */

const fs = require('fs');
const path = require('path');

const WEB = __dirname;
const SRC = path.resolve(WEB, '..', 'src');
const OUT = path.join(WEB, 'public');

const MODE = (() => {
  const arg = process.argv.slice(2).find(a => a.indexOf('--backend=') === 0);
  const value = arg ? arg.split('=')[1] : 'demo';
  if (['demo', 'http'].indexOf(value) < 0) throw new Error('--backend must be demo or http, got: ' + value);
  return value;
})();

const PAGES = {
  'Page_Dashboard.html': 'dashboard.js',
  'Page_Assets.html': 'assets.js',
  'Page_AssetDetail.html': 'asset-detail.js',
  'Page_Import.html': 'import.js',
  'Page_Masters.html': 'masters.js',
  'Page_Audit.html': 'audit.js'
};

const BANNER = name =>
  '/* GENERATED by web/build.js from src/' + name + ' — do not edit this copy. */\n';

function read(p) { return fs.readFileSync(p, 'utf8'); }

function write(rel, content) {
  const target = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content);
  return target;
}

/** Pulls the contents of the single <script> or <style> block out of an HTML partial. */
function extract(file, tag) {
  const html = read(file);
  const m = html.match(new RegExp('<' + tag + '[^>]*>([\\s\\S]*)<\\/' + tag + '>'));
  if (!m) throw new Error('No <' + tag + '> block found in ' + path.basename(file));
  return m[1].replace(/^\r?\n/, '');
}

/** Keeps the block for this mode, drops the other. */
function applyMode(html) {
  const keep = MODE === 'demo' ? 'DEMO' : 'HTTP';
  const drop = MODE === 'demo' ? 'HTTP' : 'DEMO';
  return html
    .replace(new RegExp('<!--BEGIN ' + drop + '-->[\\s\\S]*?<!--END ' + drop + '-->', 'g'), '')
    .replace(new RegExp('<!--(BEGIN|END) ' + keep + '-->', 'g'), '');
}

function build() {
  // Clear the contents rather than the directory itself: on Windows a running
  // static server (or an open shell) holds a handle on the folder and rmSync
  // fails with EPERM.
  if (fs.existsSync(OUT)) {
    fs.readdirSync(OUT).forEach(entry => {
      fs.rmSync(path.join(OUT, entry), { recursive: true, force: true, maxRetries: 3, retryDelay: 100 });
    });
  } else {
    fs.mkdirSync(OUT, { recursive: true });
  }

  const written = [];

  // 1. Styles
  written.push(write('styles.css', BANNER('ui/Styles.html') + extract(path.join(SRC, 'ui/Styles.html'), 'style')));

  // 2. Server logic — demo build only. In http mode it lives in the functions.
  if (MODE === 'demo') {
    fs.readdirSync(SRC).filter(f => f.endsWith('.gs')).sort().forEach(f => {
      written.push(write('js/backend/' + f.replace(/\.gs$/, '.js'), BANNER(f) + read(path.join(SRC, f))));
    });
  }

  // 3. Client core and pages — identical in both modes.
  written.push(write('js/app.js', BANNER('ui/App.js.html') + extract(path.join(SRC, 'ui/App.js.html'), 'script')));
  Object.keys(PAGES).forEach(src => {
    written.push(write('js/pages/' + PAGES[src], BANNER('ui/' + src) + extract(path.join(SRC, 'ui', src), 'script')));
  });

  // 4. Shell and the transport for this mode.
  written.push(write('index.html', applyMode(read(path.join(WEB, 'src', 'index.html')))));
  const extras = MODE === 'demo'
    ? ['host-browser.js', 'local-transport.js']
    : ['http-transport.js'];
  extras.forEach(f => written.push(write('js/' + f, read(path.join(WEB, 'src', f)))));

  // 5. Verify every script/stylesheet the shell asks for actually landed.
  const shell = read(path.join(OUT, 'index.html'));
  const refs = [...shell.matchAll(/(?:src|href)="([^"]+\.(?:js|css))"/g)].map(m => m[1]);
  const missing = refs.filter(r => !fs.existsSync(path.join(OUT, r)));
  if (missing.length) throw new Error('index.html references files the build did not produce: ' + missing.join(', '));

  // Anything generated but unreferenced is dead weight in the bundle.
  const shipped = written
    .map(f => path.relative(OUT, f).split(path.sep).join('/'))
    .filter(f => f !== 'index.html' && f !== 'styles.css');
  const orphans = shipped.filter(f => refs.indexOf(f) < 0);
  if (orphans.length) throw new Error('These files were built but nothing references them: ' + orphans.join(', '));

  // 6. Nothing may reach outside the bundle.
  if (/(?:src|href)="(https?:)?\/\//.test(shell)) {
    throw new Error('index.html references an external origin; this build must be self-contained.');
  }
  if (MODE === 'http' && shell.indexOf('js/backend/') >= 0) {
    throw new Error('The http build must not ship the server logic to the browser.');
  }

  const bytes = written.reduce((n, f) => n + fs.statSync(f).size, 0);
  console.log('Built ' + written.length + ' files (' + Math.round(bytes / 1024) + ' KB) into ' + OUT +
    ' [backend: ' + MODE + ']');
  console.log('Referenced and present: ' + refs.length + ' assets.');
}

build();
